// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsgtzykbcihcntbcycyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzZ3R6eWtiY2loY250YmN5Y3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDMwNTIsImV4cCI6MjA2NjAxOTA1Mn0.X_9Zazrdb6NVIJidtCXKTyGcVNW0Fe9pHtB5US07YjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);